config/routes.rb
Demo::Application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  root to: 'products#index', as: 'root'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/bonus', to: 'static_pages#bonus', as: 'bonus'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/vopros', to: 'static_pages#vopros', as: 'vopros'


  resources :orders, :carts, :users
  resources :sessions , only: [:new, :create, :destroy]
  get "/products/:id", to: 'products#show', as: 'product'
  resources :products
    resources :line_items do
      member do
        get 'remove_item'
      end
    end
  

match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  get "store/index"

  
  get "/:menu/:category", to: 'products#index_category', as: 'category'
  get "/:menu/:category/:subcategory", to: 'products#index_subcategory', as: 'subcategory'
  get "/:menu", to: 'products#index_menu', as: 'menu'
  
  resources :menus



end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity+=1
		else
        	current_item = line_items.build(product_id: product_id)
        end
        current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

	def total_quantity
		line_items.to_a.sum { |item| item.quantity }
	end

	def remove_item(id)
		current_item = line_items.find_by_id(id)
		if current_item.quantity > 1
			current_item.quantity-=1
			current_item.save
		else
			current_item.quantity=0
        	current_item.destroy
        end
        current_item || id
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories, dependent: :destroy
	has_many :products
	belongs_to :menu

	
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
	belongs_to :cart

	def total_price
		product.price * quantity
	end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :categories
	has_many :subcategories, through: :categories
	has_many :products, through: :subcategories
end

app/models/option_type.rb
class OptionType < ActiveRecord::Base
	has_many :option_values
end

app/models/option_value.rb
class OptionValue < ActiveRecord::Base
	belongs_to :option_type

	has_many :product_option_values
	has_many :products, through: :product_option_values

	def quantity
		product_option_values.first.quantity || 0
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	

	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES
	def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	belongs_to :interest
	belongs_to :prototype

	has_many :line_items
	has_many :properties, through: :prototype
	has_many :product_option_values
	has_many :property_values
	has_many :option_values, through: :product_option_values
	before_destroy :ensure_not_referenced_by_any_line_item

	#attr_accessible :articul, :title, :proizvoditel, :price, :price_discount, :price_second, :kol_v_upakovke
	#attr_accessible :category, :subcategory, :discount, :hit, :is_show, :vsego, :reserv
	#attr_accessible :svobod_ostatok, :is_new, :description, :image_url, :is_show, :category_id, :subcategory_id, :menu_id, :interest_id						


	# scope :subcategory (where category)
	def self.search(page,number=9,order='title')
	  paginate :per_page => number, :page => page,
	           # :conditions => ['name like ?', "%#{search}%"],
	           :order => order
	end

	
	def add_product_option(product_id,value_id)
		current_product = Product.find(product_id)
		option = current_product.product_option_values.where(product_id:product_id, option_value_id: value_id)

		if option
			option.quantity+=1
		else
			option.build
        end
        option
	end

	#validates :title, :description, :image_url, presence: true
    #validates :price, numericality: {greater_than_or_equal_to: 0.01}
    #validates :title, uniqueness: true
    #validates :image_url, allow_blank: true, format: {
	 #   with: %r{\.(gif|jpg|png)\z}i,
	  #  message: 'must be a URL for GIF, JPG or PNG image.'
	    # URL должен указывать на изображение формата GIF, JPG или PNG
	#}

	
	#...
	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
	    if line_items.empty?
	        return true
	    else
	        errors.add(:base, 'существуют товарные позиции')
	        return false
	    end
	end
end

app/models/property.rb
class Property < ActiveRecord::Base
	# должно быть Property а не  Properies
	has_many :property_values
	has_many :prototype_properties
	has_many :prototype, through: :prototype_properties
end

app/models/property_value.rb
class PropertyValue < ActiveRecord::Base
	belongs_to :property
	belongs_to :product

end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
	has_many :products
	has_many :prototype_properties
	has_many :properties, through: :prototype_properties
end

app/models/prototype_property.rb
class PrototypeProperty < ActiveRecord::Base
	belongs_to :prototype
	belongs_to :property
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	belongs_to :menu
	has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    redirect_to store_url
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    redirect_to store_url
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to store_url }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Попытка доступа к несуществующей корзине #{params[:id]}"
      redirect_to store_url, notice: 'Несуществующая корзина'

      else
        
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_div_if(condition, attributes = {}, &block) 
		if condition
			attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/_cart.html.erb
<div class="top_cart" id="top_cart" style="" >
	<div class="cart_items" >
		<div id="cart_items" class="cart_wrap">
					<h3>Корзина</h3>
					<div class="cart_scroller">
						<table cellpadding="0" cellspacing="0" class="cart_list">
							<tbody>
										<%= render cart.line_items %>
						</tbody></table>
					</div>
					<span class="s"></span>
					<table cellpadding="0" cellspacing="0" class="cart_list">
						<tbody><tr class="last">
							<td class="del"><p style="width: 13px"></p></td>
							<td class="photo"><p style="width: 60px"></p></td>
							<td colspan="1" class="title t_title" style="width: 100%">
								<h2>Итого</h2>
								<!-- a href="javascript://" onclick="clearCart(); return false" class="button_gray"><span>отменить</span></a -->
							</td>
							<td class="price" style="text-align: right">
								<h2>
									<%= cart.total_price unless cart.nil? %> р
									<br>
								</h2>
							</td>
							<td>
								<%= button_to "Оформить", new_order_path, method: :get %>
								<%= button_to 'Очистить корзину', cart,  method: :delete, data: { confirm: 'Are you sure?' }%>
							</td>
						</tr>
					</tbody></table>
				</div>
	</div>
	<div id="cart_title" class="cart_title" onclick="cart();">
		<div class="opened"><p class="cart_counts">Итого: <small><%= cart.total_price %>р</small></p>
				<h3><small class="filled"><%= cart.total_quantity %></small> Корзина</h3>
		</div>
		<div class="closed">
			<span>^</span>свернуть



			</div>
	</div>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>