config/routes.rb
Demo::Application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  root to: 'products#index', as: 'root'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/bonus', to: 'static_pages#bonus', as: 'bonus'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/vopros', to: 'static_pages#vopros', as: 'vopros'


  resources :orders, :carts, :users
  resources :sessions , only: [:new, :create, :destroy]
  get "/products/:id", to: 'products#show', as: 'product'
  resources :products
    resources :line_items do
      member do
        get 'remove_item'
      end
    end
  

match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  get "store/index"

  
  get "/:menu/:category", to: 'products#index_category', as: 'category'
  get "/:menu/:category/:subcategory", to: 'products#index_subcategory', as: 'subcategory'
  get "/:menu", to: 'products#index_menu', as: 'menu'
  
  resources :menus



end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	belongs_to :interest
	belongs_to :prototype

	has_many :line_items
	has_many :properties, through: :prototype
	has_many :product_option_values
	has_many :property_values
	has_many :option_values, through: :product_option_values
	before_destroy :ensure_not_referenced_by_any_line_item

	#attr_accessible :articul, :title, :proizvoditel, :price, :price_discount, :price_second, :kol_v_upakovke
	#attr_accessible :category, :subcategory, :discount, :hit, :is_show, :vsego, :reserv
	#attr_accessible :svobod_ostatok, :is_new, :description, :image_url, :is_show, :category_id, :subcategory_id, :menu_id, :interest_id						


	# scope :subcategory (where category)
	def self.search(page,number=9,order='title')
	  paginate :per_page => number, :page => page,
	           # :conditions => ['name like ?', "%#{search}%"],
	           :order => order
	end

	
	def add_product_option(product_id,value_id)
		current_product = Product.find(product_id)
		option = current_product.product_option_values.where(product_id:product_id, option_value_id: value_id)

		if option
			option.quantity+=1
		else
			option.build
        end
        option
	end

	#validates :title, :description, :image_url, presence: true
    #validates :price, numericality: {greater_than_or_equal_to: 0.01}
    #validates :title, uniqueness: true
    #validates :image_url, allow_blank: true, format: {
	 #   with: %r{\.(gif|jpg|png)\z}i,
	  #  message: 'must be a URL for GIF, JPG or PNG image.'
	    # URL должен указывать на изображение формата GIF, JPG или PNG
	#}

	
	#...
	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
	    if line_items.empty?
	        return true
	    else
	        errors.add(:base, 'существуют товарные позиции')
	        return false
	    end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :category, :set_cart
  
  
  # GET /products
  # GET /products.json

  def index
    # @products ||= Product.search params[:page]
    render 'static_pages/main'
  end

  def index_menu
    @products = @current_menu.products.search(params[:page]) if @current_menu
    # @products ||= Product.search params[:page]
    render action: :index
  end

  def index_category
    @products = @current_category.products.search(params[:page]) 
    render action: :index
  end

  def index_subcategory
    if @current_subcategory.nil?
      redirect_to action: 'index' 
      return
    end
    @products =  @current_subcategory.products.search(params[:page])
    render action: :index
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @option_values = Product.find(1).option_values
    respond_to do |format|
        format.html {}
        format.js { product = @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
    @subcategories = @product.category.subcategories.map { |cat| [cat.name, cat.id]}
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        # format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        flash[:success] = "Successfully updated..."
        flash[:notice]  = params
        format.html { redirect_to action: :products, controller: :admin }
        # format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def category
      @interests = Interest.all.map { |n| [n.name, n.id] }
      @menu = Menu.includes(:categories).includes(:subcategories).all
      @current_menu = Menu.includes(:categories).find_by_permalink([params[:menu]]) if params[:menu]
      if @current_menu.nil? and params[:menu]
        redirect_to action: 'index'
        return
      end
      @current_category = @current_menu.categories.find_by_url_name(params[:category]) if params[:category]
      @current_subcategory = @current_category.subcategories.find_by_url_name(params[:subcategory]) if params[:subcategory]
      @properties=Prototype.first.properties
    end

    def set_cart
      @cart = current_cart  
    end

 # Never trust parameters from the scary internet, only allow the white list through.
    # def product_params
    #   params.require(:product).permit(:title, :description, :image_url, :price, :interest_id, :category_id, :subcategory_id, option_values: [:id,:value])
    # end
    def product_params
      params.require(:product).permit(
        :category_id, :subcategory_id, :interest_id, :prototype_id,:articul, :title, :proizvoditel, :price, :price_discount, :price_second, :price_second_discount, :kol_v_upakovke,
        :discount, :hit,:is_show,:vsego,:reserv,:svobod_ostatok,:is_new,:description,:image_url,:id)
    end
    def option_params
      params.require(:subcategory).permit(:id, :name, :title, :url_name)      
    end

    def record_not_found
      # flash.now[:notice] = "Товар или категория товаров не найдены"  
      redirect_to action: 'index'
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, @categories.map { |cat| [cat.name, cat.id]}, prompt: '...' %>
  </div>
  <div class="field">
    <%= f.label :subcategory_id %><br>
    <%= f.select :subcategory_id, @subcategories, prompt: '...' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
     <div class="one_product border">
        <% if (1..100).to_a.shuffle.first > 70 %>
        <div id="best_seller">
            <%= image_tag ("ribbon_best_seller.png"), size: "50x65" %>
        </div>
        <% end %>
        <%= link_to "#{product.title} (#{product.id})", product_path(product), class: "title_item" %>
         <%= image_tag (product.image_url), size: "170x170" %><BR>
         <%= link_to 'Предварительный просмотр', product_path(product), remote: true %>
         <div class="price_line">
                <p class="price"><%= product.price %> р</p>
             <%= button_to "В корзину", line_items_path(product_id: product), remote: true, class: "btn btn-sm btn-primary"  %>
         </div>
         
         <div class="left">
             <% if product.subcategory %> 
             <small>Kатегория"<%= product.category.name %>"</small><br>
             <% end %>

             <% if !product.subcategory.nil? %> 
             <small>Подкатегория"<%= product.subcategory.name %>"</small><br>
             <% end %>
         </div>
     </div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="main" class="col-md-10">
	<div id="store">
		<div class="row">
			 <%= page_entries_info @posts %>
			 <%= will_paginate @products, :container => "<div>", class: "col-md-4" %>
		</div>
		<div class="row">
			<%= render @products %>
		</div>
	</div>

	<div id="predv_prosmotr" class="border">
		<%= image_tag 'close.png', class: "predv_close" %>
	    <div id="windowContent"></div>
	</div>
	<div id="overlay"></div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/predv_prosmotr.html.erb
<h2><%= @product.title %></h2>
<!-- основная часть продукта -->
<div class="row">
  <div class="col-md-8 center">  <%= image_tag @product.image_url %></div>
  <div class="col-md-4 center">
    <div class="border">
          выбор варианта продукта
       <h6>Цена:</h6> 
        <h2><%= @product.price %>p</h2>
              <% @option_values.each do |n| %>
              <%= fields_for n do |o| %>
              <input type="button" value="+" name="1" id="addone">
              <%= n.title %>  <%= o.text_field :quantity, size: 1 %><br>
      <% end end %>

        <%= button_to 'Add to Cart', line_items_path(product_id: @product), remote: true, class: "btn btn-primary" %> 
    </div>
     
  </div>
    <div class="row">
      <div class="col-md-12 center">
        <div class="border">
            <h3>Дополнительный блок</h3> 
        </div>
      </div>
    </div>
    </div>
  </div>

  <!-- описание -->
<div class="row">
  <div class="col-md-12 center">
    <div class="border">
      Описание
      <h6><%= @product.description %></h6>
    </div>
  </div>
</div>

  <!-- купите в комплекте -->
<div class="row">
  <div class="border">
    <h3>Купите в комплекте</h3>
    <div class="col-md-2 center">1</div>
    <div class="col-md-2 center">2</div>
    <div class="col-md-2 center">3</div>
    <div class="col-md-2 center">4</div>
    <div class="col-md-2 center">5</div>
    <div class="col-md-2 center">6</div>
    <BR>
    <BR>
    <BR>
    </div>
 </div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h2 class="page-header"><%= @product.title %></h2>
<!-- основная часть продукта -->
<div class="row">
  <div class="col-md-8 center">  <%= image_tag @product.image_url %></div>
  <div class="col-md-4 center">
    <div class="border">
          выбор варианта продукта
       <h6>Цена:</h6> 
        <h2><%= @product.price %>p</h2>
              <% @option_values.each do |n| %>
              <%= fields_for n do |o| %>
              <%= n.title %>  <%= o.text_field :quantity, size: 1 %><br>
      <% end end %>

        <%= button_to 'Add to Cart', line_items_path(product_id: @product), remote: true, class: "btn btn-primary" %> 
    </div>
     
  </div>
    <div class="row">
      <div class="col-md-12 center">
        <div class="border">
            <h3>Дополнительный блок</h3> 
        </div>
      </div>
    </div>
    </div>
  </div>

  <!-- описание -->
<div class="row">
  <div class="col-md-12 center">
    <div class="border">
      Описание
      <h6><%= @product.description %></h6>
    </div>
  </div>
</div>

  <!-- купите в комплекте -->
<div class="row">
  <div class="border">
    <h3>Купите в комплекте</h3>
    <div class="col-md-2 center">1</div>
    <div class="col-md-2 center">2</div>
    <div class="col-md-2 center">3</div>
    <div class="col-md-2 center">4</div>
    <div class="col-md-2 center">5</div>
    <div class="col-md-2 center">6</div>
    <BR>
    <BR>
    <BR>
    </div>
 </div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/show.js.erb
$('#windowContent').html("<%=j render template: 'products/predv_prosmotr', collection: @product %>");
$('#predv_prosmotr').css({'display':'block'});
$("#overlay").show();