config/routes.rb
Demo::Application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  root to: 'products#index', as: 'root'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/bonus', to: 'static_pages#bonus', as: 'bonus'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/vopros', to: 'static_pages#vopros', as: 'vopros'


  resources :orders, :carts, :users
  resources :sessions , only: [:new, :create, :destroy]
  get "/products/:id", to: 'products#show', as: 'product'
  resources :products
    resources :line_items do
      member do
        get 'remove_item'
      end
    end
  

match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  get "store/index"

  
  get "/:menu/:category", to: 'products#index_category', as: 'category'
  get "/:menu/:category/:subcategory", to: 'products#index_subcategory', as: 'subcategory'
  get "/:menu", to: 'products#index_menu', as: 'menu'
  
  resources :menus



end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
	belongs_to :cart

	def total_price
		product.price * quantity
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to products_url }
        format.js { @current_item = @line_item }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  def remove_item
     @cart = current_cart

     
     @line_item = @cart.remove_item(params[:id])
    if params[:del]=="1"
      @line_item.quantity=0
      @line_item.destroy
    end

    respond_to do |format|
        format.html { redirect_to store_url }
        format.js { @current_item = @line_item }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% notr ||= "no" %>
<% if line_item.product %>
	<% if notr == "no" %>
		<% if line_item == @current_item %>
			<tr class = "current_item" id = "line_item<%= line_item.id %>">
		<% else %>
			<tr id = "line_item<%= line_item.id %>">
		<% end 
	end %>
		 <td class="del">
		 	<%= link_to '', remove_item_line_item_path(del: "1" , id: line_item), remote: true %>
		 </td>
		 <td class="photo">
		 	<a href="/product/1856"><img src="http://img.ikra-ikra.ru/attach/6655/w60h60" alt=""></a>
		 </td>
		<td class="title">
			<%= line_item.product.title %>
		</td>
		 <td class="price item_price"><%= line_item.product.price %>р &times;</td>
		 <td id = "count<%= line_item.id %>" ><%= line_item.quantity %></td>
		<td class="count_td">
			<div class="count">
				<%= link_to image_tag("plus.gif", alt: '+'), remove_item_line_item_path(id: line_item), remote: true %><br /><BR>
				<%= image_tag("minus.gif") %></a>
			</div>
			
			<span class="prices"><%= line_item.total_price %>р</span>
		</td>
	<% if notr == "no" %>
			</tr>
	<%  end 
end %>

app/views/line_items/create.js.erb
if ($('#top_cart tr').length == 1) { $('#cart').show('blind', 1000); }
$('#top_cart').html("<%=j render @cart %>");
$('.current_item').css({'background-color':'#fee'}).animate({'background-color':'#fee'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/remove_item.js.erb
<% if @current_item.quantity != 0  %>
$('#line_item<%= @current_item.id %>').html("<%=j render @current_item, template: 'line_item', notr: 'yes' %>"); 
<% else %>
$('#line_item<%= @current_item.id %>').html(""); 
<% end %>
$('.current_item').css({'background-color':'#fee'}).animate({'background-color':'#fff'}, 1000);

app/views/line_items/show.html.erb
<strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>