config/routes.rb
Demo::Application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  root to: 'products#index', as: 'root'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/bonus', to: 'static_pages#bonus', as: 'bonus'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/vopros', to: 'static_pages#vopros', as: 'vopros'


  resources :orders, :carts, :users
  resources :sessions , only: [:new, :create, :destroy]
  get "/products/:id", to: 'products#show', as: 'product'
  resources :products
    resources :line_items do
      member do
        get 'remove_item'
      end
    end
  

match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  get "store/index"

  
  get "/:menu/:category", to: 'products#index_category', as: 'category'
  get "/:menu/:category/:subcategory", to: 'products#index_subcategory', as: 'subcategory'
  get "/:menu", to: 'products#index_menu', as: 'menu'
  
  resources :menus



end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity+=1
		else
        	current_item = line_items.build(product_id: product_id)
        end
        current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

	def total_quantity
		line_items.to_a.sum { |item| item.quantity }
	end

	def remove_item(id)
		current_item = line_items.find_by_id(id)
		if current_item.quantity > 1
			current_item.quantity-=1
			current_item.save
		else
			current_item.quantity=0
        	current_item.destroy
        end
        current_item || id
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories, dependent: :destroy
	has_many :products
	belongs_to :menu

	
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
	belongs_to :cart

	def total_price
		product.price * quantity
	end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :categories
	has_many :subcategories, through: :categories
	has_many :products, through: :subcategories
end

app/models/option_type.rb
class OptionType < ActiveRecord::Base
	has_many :option_values
end

app/models/option_value.rb
class OptionValue < ActiveRecord::Base
	belongs_to :option_type

	has_many :product_option_values
	has_many :products, through: :product_option_values

	def quantity
		product_option_values.first.quantity || 0
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	

	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES
	def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	belongs_to :interest
	belongs_to :prototype

	has_many :line_items
	has_many :properties, through: :prototype
	has_many :product_option_values
	has_many :property_values
	has_many :option_values, through: :product_option_values
	before_destroy :ensure_not_referenced_by_any_line_item

	#attr_accessible :articul, :title, :proizvoditel, :price, :price_discount, :price_second, :kol_v_upakovke
	#attr_accessible :category, :subcategory, :discount, :hit, :is_show, :vsego, :reserv
	#attr_accessible :svobod_ostatok, :is_new, :description, :image_url, :is_show, :category_id, :subcategory_id, :menu_id, :interest_id						


	# scope :subcategory (where category)
	def self.search(page,number=9,order='title')
	  paginate :per_page => number, :page => page,
	           # :conditions => ['name like ?', "%#{search}%"],
	           :order => order
	end

	
	def add_product_option(product_id,value_id)
		current_product = Product.find(product_id)
		option = current_product.product_option_values.where(product_id:product_id, option_value_id: value_id)

		if option
			option.quantity+=1
		else
			option.build
        end
        option
	end

	#validates :title, :description, :image_url, presence: true
    #validates :price, numericality: {greater_than_or_equal_to: 0.01}
    #validates :title, uniqueness: true
    #validates :image_url, allow_blank: true, format: {
	 #   with: %r{\.(gif|jpg|png)\z}i,
	  #  message: 'must be a URL for GIF, JPG or PNG image.'
	    # URL должен указывать на изображение формата GIF, JPG или PNG
	#}

	
	#...
	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
	    if line_items.empty?
	        return true
	    else
	        errors.add(:base, 'существуют товарные позиции')
	        return false
	    end
	end
end

app/models/property.rb
class Property < ActiveRecord::Base
	# должно быть Property а не  Properies
	has_many :property_values
	has_many :prototype_properties
	has_many :prototype, through: :prototype_properties
end

app/models/property_value.rb
class PropertyValue < ActiveRecord::Base
	belongs_to :property
	belongs_to :product

end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
	has_many :products
	has_many :prototype_properties
	has_many :properties, through: :prototype_properties
end

app/models/prototype_property.rb
class PrototypeProperty < ActiveRecord::Base
	belongs_to :prototype
	belongs_to :property
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	belongs_to :menu
	has_many :products
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_breadcrumb.html.erb
<% if @product %>
<% @current_menu ||= @product.category.menu%>
<% @current_category ||= @product.category %>
<% @current_subcategory ||= @product.subcategory %>
<% end %>
<ul class="breadcrumb">
	<% if @current_menu %>
 	<li><%= link_to @current_menu.name , menu_path(@current_menu.permalink) %> </li>
 	<% end %>
 	<% if @current_category %>
 	<li class="<%= "active" if !@current_subcategory %>" ><%= link_to @current_category.name , category_path(@current_menu.permalink,@current_category.url_name) %></li>
 	<% end %>
 	<% if @current_subcategory %>
	<li class="active">
		<%= link_to @current_subcategory.name,subcategory_path(@current_menu.permalink,@current_category.url_name,@current_subcategory.url_name) %></li>
 	<% end %>
</ul>

app/views/layouts/_categories.html.erb
<% if params[:menu] && params[:category].blank? %>
	<li class="sidebar_category">
		<%= link_to "#{params["menu"]}/#{category.url_name}" do %>
		<%= category.name %> <span class="cat-badge"><%= category.products.size %></span>
		<% end %>
	</li>
<% end %>
<% if params[:category]%>
	<li class="sidebar_category">
		<%= link_to "#{params["category"]}/#{category.url_name}" do%>
		<%= category.name %> <span class="cat-badge"><%= category.products.size %></span>
		<% end %>
	</li>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <table>
    <tr>
      <td>фильтры</td>
      <td>поиск</td>
      <td></td>
      <td id="tel"><%= image_tag "tel.png", size:"70x70" %>(495) 276-66-77</td>
      <td>обратный звонок</td>
      <td>Пн-Вт: с 9:00-21:00<br>
          Сб-Вс: с 11:00-19:00
      </td>
    </tr>
  </table>
</footer>

app/views/layouts/_header.html.erb
<div class="row">
	<ul class="nav nav-tabs">
		<li><%= link_to 'Admin', '/admin' %></li>
		<li><%= link_to 'О нас', about_path %></li>
		<li><%= link_to 'Бонус', bonus_path %></li>
		<li><%= link_to 'Контакт', contact_path %></li>
		<li><%= link_to 'Помощь', help_path %></li>
		<li><%= link_to 'Задать вопрос', vopros_path %></li>
		<li><%= link_to 'Регистрация', "#" %></li>
		<li><%= link_to 'Вход', '#' %></li>
	</ul>
</div>
<div class="row">
	<div class="col-md-2">
		<%= link_to image_tag("logo.png", class:"logo"), root_path %>
	</div>
	<div class="col-md-10">
		<div class="row">
			<div class="col-md-8">
				<div class="row header_bar" style="margin:10px 0;">
					<%= image_tag "dostavka.png", size:"40x40" %> Доставка
					<%= image_tag "oplata.png", size:"40x40" %> Оплата
					<%= image_tag "otzivi.png", size:"40x40" %> Отзывы
					<%= image_tag "news.png", size:"40x40" %> Новости
					<%= image_tag "optom.png", size:"40x40" %> Оптом
					<%= image_tag "akcii.png", size:"40x40" %> Акции
				</div>
			</div>
			<div class="col-md-4" style="padding-left:0;">
				<span class="header_tel"> <span class="gray">(495)</span> 276-66-77</span>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8" style="padding-right:8px">
				<div class="banner_top border">
					Осенний марафон подарков
				</div>
				<div class="chasi_raboti col-md-2 border">
					Пн-Вт:
					<span class="label label-info">с 9:00-21:00</span><br>
					Сб-Вс:
					<span class="label label-info">с 11:00-19:00</span>
				</div>
			</div>
			<div class="col-md-4" style="padding-left:0">
				<div class="border margin-top-5 e-mail">
					Оставьте адрес для получения E-mail рассылки с новостями и акциями.
					<div class="input-group">
						<input type="text" class="form-control">
					    <span class="input-group-btn">
					      <button class="btn btn-default" type="button">go</button>
					    </span>
			  	  	</div>
				</div>
			</div>
		</div>
			<div class="row">
				<div class="col-md-8">
					<div class="input-group">
						<input type="text" class="form-control">
					    <span class="input-group-btn">
					      <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
					    </span>
			  	  	</div><!-- /input-group -->
			  	</div>
			  	<div class="col-md-4">
			  		<div class="obratniy_zvonok">
			  			ОБРАТНЫЙ ЗВОНОК
			  		</div>
			  	</div>
			</div>
	</div>
	
	
    
</div>
<div class="container">
        <hr class="bs-docs-separator" style="margin-top:0">
        <!--Выпадающее меню-->
        <ul class="nav nav-tabs nav-tabs-top">
            <%= render @menu %>
        </ul>
    </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/_one_side_filter.html.erb
<div class="filter">
    	<div class="filter-head">
		    <span class="title">
		        <span class="g-icon-h">
		        	<span class="strelka"></span>
		        </span><b class="g-pseudo-h"><%= name %></b>
		        <span class="b-catalog-filter-item-help js-construct"></span>
		    </span>
		</div>
		<div class="filter-body">
				<% array.each do |a| %>
				<% checked = false %>
					<% checked = params[:property].include?("#{a.id}") if params[:property]  %>
	                <div>
	                	<%= check_box_tag "property[#{a.id}]", a.id, false, checked: checked || false %>
	                	<%= label_tag "property[#{a.id}]", a.value  %>
	                </div>
	            <% end %>
		</div>
	</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div id="side" class="col-md-2">
	<!-- открываем сайдбар -->
	<% if params[:subcategory].nil? and !params[:category].nil? %>
	<div class="border">
	 	<ul class="ul-category-sidebar">
			 <% if params[:menu] && params[:category].blank? %>
				<div class="pull-left">Категории</div><br>
				<%= render partial: 'layouts/categories', collection: @current_menu.categories, as: :category %>
			<% end %>
			<% if params[:category] && @current_category.subcategories.present? %>
				<div class="pull-left">Категории</div><br>
				<%= render partial: 'layouts/categories', collection: @current_category.subcategories, as: :category %>
			<% end %>
		</ul>
	</div>
	<% end %>

<% value = params[:product][:price] || 0 if params[:product] %>
<div class="border" style="padding: 10px 0">
	<div class="pull-left">Цена: <%= value %></div><br>
	
	<%= form_tag({action: "index"}, {multipart:true, method: "GET"}) do %>

		<% price = params[:product][:price] || 50 if params[:product] %>
		<%= range_field(:product, :price, in: 1..100, value: price, onclick: "submit();") %>


	
	<% @properties.each do |property| %>
		<% array = property.property_values.where(property_id: property.id) %>
		<% name = property.name %>
		<%= render partial: "layouts/one_side_filter", locals: {array: array, name: name}  %>
    <% end %>

    <%= submit_tag("Подобрать", class: "btn btn-sm btn-primary") %>
    <BR><BR>
    <% end %>
</div>
   


    <!-- закрыть сайдбар -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class='<%= controller.controller_name %> , container'>
	<%= render 'layouts/header' %>
    <%= render @cart %>
	<%= render partial: 'layouts/breadcrumb' if @current_menu %>
	<%= render 'layouts/messages' %>

	    <div class="row">
			<%= render 'layouts/sidebar' if !(action_name == 'show' or controller.controller_name == 'static_pages') %>
			<%= yield %>
		</div>

	<%= render partial: 'stuff/main4steps' if action_name == 'index' %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/stuff/_main4steps.html.erb
<div class="row main_steps">
			
				<h2>Как мы работаем?</h2>
				<div class="col-md-3">
					<div class="how-we-1">
						<h3>Вы оставляете заявку <br>на сайте или по телефону</h3>
					</div>
				</div>
				<div class="col-md-3">
					<div class="how-we-2">
						<h3>Менеджер связывается с <br> Вами для подтверждения заказа</h3>
					</div>
				</div>
				<div class="col-md-3">
					<div class="how-we-3">
						<h3>Мы быстро доставляемd Вашу <br>посылку по указанному адресу</h3>
					</div>
				</div>
				<div class="col-md-3">
					<div class="how-we-4">
						<h3>Вы получаете свой товар и платите <br>за него на почте или курьеру</h3>
					</div>
				</div>
			
		</div>

app/views/stuff/_main_banners.html.erb
<div class="row">
			<div class="col-md-3">
				<div class="banner-main">
					<p>Покупайте в нашем магазине и <BR /> получайте бонусы много.ру</p>
					<%= image_tag "banner-main.png", style:"margin-right:-15px;" %>
					<div class="banner-main-foot">Бонусы Много.ру</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="banner-main">
					<p>Получайте и <BR /> тратье бонусы СПАСИБО</p>
					<%= image_tag "banner-main-spasibo.png" %>
					<div class="banner-main-foot">Бонусы Много.ру</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="banner-main">
					<p>Лучшие цены. Еженедельное обновление</p>
					<%= image_tag "banner-main-3.png" %>
					<div class="banner-main-foot">Бонусы Много.ру</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="banner-main">
					<p>Зачем ждать? <BR />Надо брать! <BR /> Выгодный кредит <BR /> за 5 минут</p>
					<%= image_tag "banner-main-4.png" %>
					<div class="banner-main-foot">Бонусы Много.ру</div>
				</div>
			</div>
	</div>